### ISSUE TITLE
Mateusz Kupilas (JavaDevMatt)

### ISSUE THREAD

**Issue by Kacu94** [hs3city/hs3-ama#1]
Prowadzi bardzo interesujący podcast retrospektywa.com na temat projektów i problemów jakie można spotkać na swojej drodze zaczynając swój. W każdym odcinku zaprasza gościa, który właśnie o tym opowiada.

https://kupilas.pl/

**Comment by tgbdc7** [comment]
@Kacu94 Świetny pomysł :+1:

**Comment by DoomHammer** [comment]
@Kacu94 Mateusz niestety nie jest w stanie wziąć na siebie teraz kolejnej rzeczy, więc odpuszcza.
