### ISSUE TITLE
Zatrudniam do IT - na co zwracam uwagę?

### ISSUE THREAD

**Issue by zdzichu** [hs3city/hs3-ama#13]
Cześć,
Jestem kierownikiem niewielkiego zespołu IT. Co jakiś czas przeprowadzam rekrutację i pomagam też innym znaleźć pracowników. Na proces zatrudniania mam więc perspektywę pracodawcy.
Chętnie opowiem: na co zwracam uwagę, jak prowadzę rozmowy, o co chodzi z gwiazdkami i jakie profile na LinkedIn są dla mnie wartościowe.

**Comment by DoomHammer** [comment]
Termin potwierdzony: https://github.com/hs3city/hs3-ama/blob/main/README.md#rozk%C5%82ad-jazdy-sezonu-2
