### ISSUE TITLE
Mateusz Bełczowski - moje propozycje tematów (czytelnictwo, podcasty, systemy notatek, listy to-do)

### ISSUE THREAD

**Issue by MateuszBelczowski** [hs3city/hs3-ama#15]
Nie wiem, który temat cieszyłby się największym zainteresowaniem, bo przychodzą mi do głowy takie

1) Jak wyrobić sobie nawyk czytania książek
2) Co fajnego mogą zaoferować nam podcasty?
3) Moja przygoda z różnymi systemami notatek
4) Dlaczego powinieneś korzystać z list to-do

Także, jeśli którykolwiek z wymienionych tematów przypadłby Wam do gustu, to prosiłbym o informację :)

**Comment by DoomHammer** [comment]
Termin potwierdzony: https://github.com/hs3city/hs3-ama/blob/main/README.md#rozk%C5%82ad-jazdy-sezonu-2
